/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.phanmemban.view;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.WindowConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class MainBD extends javax.swing.JFrame {

    /**
     * Creates new form MainBD
     */
    public MainBD() {
        initComponents();
    }
    public MainBD(String id, String ten) {
        super(id);
        JFreeChart barchar = ChartFactory.createBarChart(ten, "Chú Thích", "Doanh Thu", crearDataset(), PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(barchar);
        chartPanel.setPreferredSize(new Dimension(630, 367));
        setContentPane(chartPanel);
        setBackground(Color.gray);
    }

    private CategoryDataset crearDataset() {
        final String escalal = "Adidas0NJJ";
        final String escala2 = "AdidasKK9";
        final String escala3 = "AdidasJh33";
        final String escala4 = "AdiasKJJH8";
        final String escala5 = "AdiasKL09";
        final String pregunta1 = "Adidas0NJJ";
        final String pregunta2 = "AdidasKK9";
        final String pregunta3 = "AdidasJh33";
        final String pregunta4 = "AdiasKJJH8";
        final String pregunta5= "AdiasKL09";

        DefaultCategoryDataset defaultCategoryDataset = new DefaultCategoryDataset();
        defaultCategoryDataset.addValue(0, escalal, pregunta1);
        defaultCategoryDataset.addValue(10, escala2, pregunta2);
        defaultCategoryDataset.addValue(0, escala3, pregunta3);
        defaultCategoryDataset.addValue(0, escala4, pregunta4);
        defaultCategoryDataset.addValue(0, escala5, pregunta5);
        return defaultCategoryDataset;
    }
    public static void main(String args[]) {
        MainBD bieuDo = new MainBD("Hệ Thống Quản Lý Cửa Hàng Bán Giày FPT", "Thống Kê");
        bieuDo.setSize(800,600);
        bieuDo.setLocationRelativeTo(null);
        bieuDo.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        bieuDo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doiTraRespository1 = new com.mycompany.phanmemban.repostority.DoiTraRespository();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.phanmemban.repostority.DoiTraRespository doiTraRespository1;
    // End of variables declaration//GEN-END:variables
}
