/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.phanmemban.view;

import com.mycompany.phanmemban.model.NhanVien;
import com.mycompany.phanmemban.model.clockTheading;
import com.mycompany.phanmemban.service.NhanVienService;
import com.mycompany.phanmemban.service.impl.NhanVienServicelmpl;
import java.awt.Insets;
import java.awt.Toolkit;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class QuanLyView extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyView
     */
    NhanVienService nvsv = new NhanVienServicelmpl();

    public QuanLyView() {
        initComponents();
        setTitle("Hệ Thống Quản Lý Cửa Hàng Bán Giày FPT");
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        this.setSize(xsize, ysize);
        initClock();
        thongTinNV();
    }

    private void initClock() {
        clockTheading ck = new clockTheading(lbclock);
        ck.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTennv = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbclock = new javax.swing.JLabel();
        btnthongke = new javax.swing.JButton();
        btntrahang = new javax.swing.JButton();
        btnnhanvien = new javax.swing.JButton();
        btnsanpham = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btngiaodichj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lehuy\\OneDrive\\Documents\\PhanMemBanGiayFPT\\PhanMemBan\\src\\main\\resource\\images\\Users.png")); // NOI18N
        jLabel2.setText("Tên Nhân Viên ");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Trạng Thái : Đang làm việc");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblTennv, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblTennv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbclock.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbclock.setForeground(new java.awt.Color(153, 153, 255));
        lbclock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbclock.setIcon(new javax.swing.ImageIcon("C:\\Users\\lehuy\\OneDrive\\Documents\\PhanMemBanGiayFPT\\PhanMemBan\\src\\main\\resource\\images\\Calendar.png")); // NOI18N
        lbclock.setText("8");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbclock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbclock, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btnthongke.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnthongke.setIcon(new javax.swing.ImageIcon("C:\\Users\\lehuy\\OneDrive\\Documents\\PhanMemBanGiayFPT\\PhanMemBan\\src\\main\\resource\\images\\Bar chart.png")); // NOI18N
        btnthongke.setText("Thống Kê");
        btnthongke.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });

        btntrahang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btntrahang.setIcon(new javax.swing.ImageIcon("C:\\Users\\lehuy\\OneDrive\\Documents\\PhanMemBanGiayFPT\\PhanMemBan\\src\\main\\resource\\images\\Refresh.png")); // NOI18N
        btntrahang.setText("Trả Hàng");
        btntrahang.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btntrahang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrahangActionPerformed(evt);
            }
        });

        btnnhanvien.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnnhanvien.setIcon(new javax.swing.ImageIcon("C:\\Users\\lehuy\\OneDrive\\Documents\\PhanMemBanGiayFPT\\PhanMemBan\\src\\main\\resource\\images\\Users.png")); // NOI18N
        btnnhanvien.setText("Quản Lý Nhân Viên");
        btnnhanvien.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhanvienActionPerformed(evt);
            }
        });

        btnsanpham.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnsanpham.setIcon(new javax.swing.ImageIcon("C:\\Users\\lehuy\\OneDrive\\Documents\\PhanMemBanGiayFPT\\PhanMemBan\\src\\main\\resource\\images\\Add to basket.png")); // NOI18N
        btnsanpham.setText("Quản Lý Sản Phẩm");
        btnsanpham.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsanphamActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon("C:\\Users\\lehuy\\OneDrive\\Documents\\PhanMemBanGiayFPT\\PhanMemBan\\src\\main\\resource\\images\\Help.png")); // NOI18N
        jButton10.setText("Đổi Mật Khẩu");
        jButton10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon("C:\\Users\\lehuy\\OneDrive\\Documents\\PhanMemBanGiayFPT\\PhanMemBan\\src\\main\\resource\\images\\Exit.png")); // NOI18N
        jButton11.setText("Kết Thúc");
        jButton11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        btngiaodichj.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btngiaodichj.setIcon(new javax.swing.ImageIcon("C:\\Users\\lehuy\\OneDrive\\Documents\\PhanMemBanGiayFPT\\PhanMemBan\\src\\main\\resource\\images\\Price list.png")); // NOI18N
        btngiaodichj.setText("Quản Lý Giao Dịch");
        btngiaodichj.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btngiaodichj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaodichjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnthongke, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntrahang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btngiaodichj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngiaodichj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntrahang, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 968, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        // TODO add your handling code here:
        ThongKeView thongKeView = new ThongKeView();

        thongKeView.setVisible(true);
        thongKeView.setSize(1200, 840);
        thongKeView.setLocation(370, 120);
        thongKeView.setDefaultCloseOperation(HomeView.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnthongkeActionPerformed
    private void thongTinNV() {
        NhanVien NV = new NhanVien();
        NhanVien ons = nvsv.getOnes(NV.getUser());
        lblTennv.setText(ons.getHo() + "  " + ons.getTenDem() + "  " + ons.getTen());
    }
    private void btntrahangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrahangActionPerformed
        // TODO add your handling code here:
        DoiTraView doiTraView = new DoiTraView();
        doiTraView.setVisible(true);
        doiTraView.setLocation(350, 120);
        doiTraView.setDefaultCloseOperation(HomeView.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btntrahangActionPerformed

    private void btnnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhanvienActionPerformed
        // TODO add your handling code here:
        QuanLyNhanVien quanLyNhanVien = new QuanLyNhanVien();
        quanLyNhanVien.setVisible(true);
        quanLyNhanVien.setDefaultCloseOperation(HomeView.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnnhanvienActionPerformed

    private void btnsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsanphamActionPerformed
        // TODO add your handling code here:
        QuanLySanPham quanLySanPham = new QuanLySanPham();
        quanLySanPham.setVisible(true);
        quanLySanPham.setSize(1430, 900);
        quanLySanPham.setLocation(350, 70);
        quanLySanPham.setDefaultCloseOperation(HomeView.DISPOSE_ON_CLOSE);

        //        pack();
    }//GEN-LAST:event_btnsanphamActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        DoiMatKhauView doiMatKhauView = new DoiMatKhauView();
        doiMatKhauView.setVisible(true);
        doiMatKhauView.setLocationRelativeTo(null);
        //        doiMatKhauView.setDefaultCloseOperation(HomeView.DISPOSE_ON_CLOSE);
        //doiMatKhauView.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DangNhapView dangNhapView = new DangNhapView();
        dangNhapView.setVisible(true);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void btngiaodichjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaodichjActionPerformed
        // TODO add your handling code here:
        QuanLyGiaoDich quanLyGiaoDich = new QuanLyGiaoDich();
        quanLyGiaoDich.setVisible(true);
        quanLyGiaoDich.setSize(1510, 910);
        quanLyGiaoDich.setLocation(350, 120);
        quanLyGiaoDich.setDefaultCloseOperation(HomeView.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btngiaodichjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngiaodichj;
    private javax.swing.JButton btnnhanvien;
    private javax.swing.JButton btnsanpham;
    private javax.swing.JButton btnthongke;
    private javax.swing.JButton btntrahang;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbclock;
    private javax.swing.JLabel lblTennv;
    // End of variables declaration//GEN-END:variables
}
